development:
  adapter: postgresql
  host: localhost
  database: photo_share
  username: pguser
  password: pguser

test:
  adapter: postgresql
  database: photo_share
  host: localhost
  username: pguser
  password: pguser